# Generated by Django 5.2.1 on 2025-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="description",
            field=models.CharField(default="Default description", max_length=500),
        ),
        migrations.AddField(
            model_name="feature",
            name="name",
            field=models.CharField(default="Default name", max_length=100),
            preserve_default=False,
        ),
    ]
