# Generated by Django 5.2.1 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_feature_description_feature_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="description",
        ),
        migrations.AddField(
            model_name="feature",
            name="age",
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feature",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="details",
            field=models.CharField(default="Default Details", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feature",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
