# Generated by Django 5.2.1 on 2025-07-02 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_blog_delete_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
